### ISSUE TITLE
Need a link back to the read.me on Github

### ISSUE THREAD

**Issue by mck231** [mck231/capybera-json-parser#2]
As a user i need to find a button or link that takes me to github readme

Some where on the page we need to create a link to github readme.

dev notes: this could be in the footer or at the bottom of the side tool bar. Discuss with team. Also button should just be github icon.

**Comment by pushkarsingh019** [comment]
I would like to work on this !

**Comment by mck231** [comment]
done in c55c57ee515bd2f89cafb69f61c5544d570d412b
